dn_base: ~/work/mutant/log/ycsb/mutant-overhead

# With 10 K IOPS
#unmodified_db:        180102-233916/ycsb/180103-045616.929-d
#computation_overhead: 180103-011127/ycsb/180103-062835.306-d
#io_overhead:          180103-011200/ycsb/180103-062835.782-d

# So with the computation overhead, it uses less CPU.
#   It must have been from the unstable cloud performance, where the latter's IO overhead was somehow smaller.
#     It drives me crazy.
#     Tried user time only and user+kernel, but none of them looked good.
unmodified_db:        1/180105-004823/ycsb/180105-081022.523-d
computation_overhead: 1/180105-031211/ycsb/180105-082850.700-d

# cost_slo_epsilon 0.1
io_overhead: by-cost-slo-epsilons/180122-185607/ycsb/180123-000516.030-d

# This had extra SSTable movements
# cost_slo_epsilon 0.0
#io_overhead: by-cost-slo-epsilons/180119-175723/ycsb/180119-230659.615-d

# These included extra SSTables when a temperature-triggered migration is executed.
#io_overhead:          1/180105-031503/ycsb/180105-083222.854-d
#io_overhead:          cost-slo-epsilon/180117-181337/ycsb/180117-232324.094-d
#io_overhead:          cost-slo-epsilon/180117-181400/ycsb/180117-232324.310-d

# These 2 included grandparents for calculating the output sstable path id, which turned out to be wrong.
#io_overhead:          180108-185724/ycsb/180109-050525.028-d.bz2
#io_overhead:          180108-192308/ycsb/180109-050503.292-d.bz2
